### ISSUE TITLE
vips2webp: unable to encode

### ISSUE THREAD

**Issue by legopin** [imgproxy/imgproxy#420]
## Env
```
imgproxy:v2.13.1

IMGPROXY_MAX_SRC_RESOLUTION=50
```

## Expected Behavior
Given this very narrow and long JPG, imgproxy should return it resized

<details><summary>large source image 19034 x 800 px</summary>
[c368f320-209e-4aff-ae39-0392336439bc](https://user-images.githubusercontent.com/15863509/85117008-c0344400-b250-11ea-84e3-94cd841de110.jpeg)
</details>
## Actual Behavior
imgproxy returned 500 error with this message in the logs:
```
{
  "jsonPayload": {
    "request_id": "H2Vga055jdzmzXrkHOF-8",
    "msg": "Completed in 293.464124ms /SIGNATURE/w:1200/SOURCE",
    "status": 500,
    "stack": "/app/vips.go:213 main.(*vipsImage).Save\n/app/process.go:770 main.processImage\n/app/processing_handler.go:189 main.handleProcessing\n/app/server.go:85 main.withCORS.func1\n/app/router.go:100 main.(*router).ServeHTTP\n/usr/local/go/src/net/http/server.go:2808 net/http.serverHandler.ServeHTTP\n/usr/local/go/src/net/http/server.go:1896 net/http.(*conn).serve\n/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit",
    "error": "vips2webp: unable to encode\n",
    "method": "GET",
    "level": "error"
  },
```

Bringing the image width down to 480 allows the image to resize with no error. 
We are not too sure why the output webp image size exceeds `libvips`'s ability to resize the image.

Could you give us any pointers on how to report this to upstream?

**Comment by legopin** [comment]
After digging around the code for libvips, I found out that it is a limitation set by the webp encoder library

> 'picture' must be less than 16384x16384 in dimension (cf WEBP_MAX_DIMENSION)

![Screen Shot 2020-06-19 at 6 10 25 PM](https://user-images.githubusercontent.com/15863509/85121858-2bcddf80-b258-11ea-9a5f-560fca5ab7a9.png)
https://chromium.googlesource.com/webm/libwebp/+/refs/heads/master/src/webp/encode.h

Our image exceeded this size limit and caused error. 

Would it be a good idea to add this to the documentation as a caveat for webp resizing?

When resizing images to webp format, the source image dimensions must not exceed 16384 in either width or height.

**Comment by legopin** [comment]
Turns out with further research, this is an inherent limitation in the spec for WEBP

https://tools.ietf.org/html/rfc6386#section-18.1
> For practical reasons, VP8 imposes a motion vector size range
   limit of -4096 to 4095 full pixels, regardless of image size (VP8
   defines 14 raw bits for width and height; 16383x16383 is the maximum
   possible image size).  Bitstream-compliant encoders and decoders
   shall enforce this limit.

**Comment by DarthSim** [comment]
Hi!
Thanks for digging into this. I should definitely add this check to imgproxy.

**Comment by DarthSim** [comment]
Fixed in master

**Comment by legopin** [comment]
@DarthSim 

Can I confirm that with the fix in 399995deea642e8e50ae8ab9d1d1341c5ea12671 the following happens

1. processing option width or height causes resulting image width or height to exceed 16383
1. The width and height are shrunken down to within the limit size with a warning logged, returning image

Currently, on 2.14.1, I still have problems resizing the sample image included in the original issue.
1. original image: `jpeg width:800 height:19034`
2. processing options `w:1200` without enlarge
3. returns 500 error  `vips2webp: unable to encode`

**Comment by DarthSim** [comment]
My bad, I didn't fix the case where one of the dimensions is not specified.

**Comment by DarthSim** [comment]
Should be fixed in the latest build. The new solution is more stable yet less optimal, but since this case is not a common one I think this should be ok.
